# Generated by Django 4.1.6 on 2023-02-06 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id_credito', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_desembolso', models.DateField()),
                ('numero_cuotas', models.PositiveIntegerField()),
                ('frecuencia_de_pago', models.CharField(max_length=100)),
                ('ciclo', models.PositiveIntegerField()),
                ('id_asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.asesor')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamo.tipodecredito')),
            ],
        ),
    ]
